apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
    field.cattle.io/creatorId: user-zl5gh
    field.cattle.io/publicEndpoints: '[{"addresses":["172.17.186.109"],"port":8123,"protocol":"TCP","serviceName":"storage:clickhouse-nodeport","allNodes":true},{"addresses":["172.17.186.109"],"port":9000,"protocol":"TCP","serviceName":"storage:clickhouse-nodeport","allNodes":true},{"addresses":["172.17.186.109"],"port":9009,"protocol":"TCP","serviceName":"storage:clickhouse-nodeport","allNodes":true}]'
  creationTimestamp: null
  generation: 1
  labels:
    cattle.io/creator: norman
    workload.user.cattle.io/workloadselector: deployment-storage-clickhouse
  managedFields:
  - apiVersion: apps/v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .: {}
          f:field.cattle.io/creatorId: {}
          f:field.cattle.io/publicEndpoints: {}
        f:labels:
          .: {}
          f:cattle.io/creator: {}
          f:workload.user.cattle.io/workloadselector: {}
      f:spec:
        f:progressDeadlineSeconds: {}
        f:replicas: {}
        f:revisionHistoryLimit: {}
        f:selector: {}
        f:strategy:
          f:rollingUpdate:
            .: {}
            f:maxSurge: {}
            f:maxUnavailable: {}
          f:type: {}
        f:template:
          f:metadata:
            f:annotations:
              .: {}
              f:cattle.io/timestamp: {}
              f:field.cattle.io/ports: {}
            f:labels:
              .: {}
              f:workload.user.cattle.io/workloadselector: {}
          f:spec:
            f:containers:
              k:{"name":"clickhouse"}:
                .: {}
                f:env:
                  .: {}
                  k:{"name":"nofile"}:
                    .: {}
                    f:name: {}
                    f:value: {}
                  k:{"name":"privileged"}:
                    .: {}
                    f:name: {}
                    f:value: {}
                  k:{"name":"ulimit"}:
                    .: {}
                    f:name: {}
                    f:value: {}
                f:image: {}
                f:imagePullPolicy: {}
                f:name: {}
                f:ports:
                  .: {}
                  k:{"containerPort":8123,"protocol":"TCP"}:
                    .: {}
                    f:containerPort: {}
                    f:name: {}
                    f:protocol: {}
                  k:{"containerPort":9000,"protocol":"TCP"}:
                    .: {}
                    f:containerPort: {}
                    f:name: {}
                    f:protocol: {}
                  k:{"containerPort":9009,"protocol":"TCP"}:
                    .: {}
                    f:containerPort: {}
                    f:name: {}
                    f:protocol: {}
                f:resources: {}
                f:securityContext:
                  .: {}
                  f:allowPrivilegeEscalation: {}
                  f:capabilities: {}
                  f:privileged: {}
                  f:readOnlyRootFilesystem: {}
                  f:runAsNonRoot: {}
                f:stdin: {}
                f:terminationMessagePath: {}
                f:terminationMessagePolicy: {}
                f:tty: {}
                f:volumeMounts:
                  .: {}
                  k:{"mountPath":"/var/lib/clickhouse"}:
                    .: {}
                    f:mountPath: {}
                    f:name: {}
                  k:{"mountPath":"/var/log/clickhouse-server"}:
                    .: {}
                    f:mountPath: {}
                    f:name: {}
            f:dnsPolicy: {}
            f:restartPolicy: {}
            f:schedulerName: {}
            f:securityContext: {}
            f:terminationGracePeriodSeconds: {}
            f:volumes:
              .: {}
              k:{"name":"clickhouse-data"}:
                .: {}
                f:hostPath:
                  .: {}
                  f:path: {}
                  f:type: {}
                f:name: {}
              k:{"name":"clickhouse-log"}:
                .: {}
                f:hostPath:
                  .: {}
                  f:path: {}
                  f:type: {}
                f:name: {}
    manager: rancher
    operation: Update
    time: "2023-02-27T06:52:44Z"
  - apiVersion: apps/v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          f:deployment.kubernetes.io/revision: {}
      f:status:
        f:availableReplicas: {}
        f:conditions:
          .: {}
          k:{"type":"Available"}:
            .: {}
            f:lastTransitionTime: {}
            f:lastUpdateTime: {}
            f:message: {}
            f:reason: {}
            f:status: {}
            f:type: {}
          k:{"type":"Progressing"}:
            .: {}
            f:lastTransitionTime: {}
            f:lastUpdateTime: {}
            f:message: {}
            f:reason: {}
            f:status: {}
            f:type: {}
        f:observedGeneration: {}
        f:readyReplicas: {}
        f:replicas: {}
        f:updatedReplicas: {}
    manager: kube-controller-manager
    operation: Update
    time: "2023-02-27T06:54:17Z"
  name: clickhouse
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      workload.user.cattle.io/workloadselector: deployment-storage-clickhouse
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      annotations:
        cattle.io/timestamp: "2023-02-27T06:52:43Z"
        field.cattle.io/ports: '[[{"containerPort":8123,"dnsName":"clickhouse-nodeport","hostPort":0,"kind":"NodePort","name":"clickhouse8123","protocol":"TCP","sourcePort":8123},{"containerPort":9000,"dnsName":"clickhouse-nodeport","hostPort":0,"kind":"NodePort","name":"clickhouse9000","protocol":"TCP","sourcePort":9000},{"containerPort":9009,"dnsName":"clickhouse-nodeport","hostPort":0,"kind":"NodePort","name":"clickhouse9009","protocol":"TCP","sourcePort":9009}]]'
      creationTimestamp: null
      labels:
        workload.user.cattle.io/workloadselector: deployment-storage-clickhouse
    spec:
      containers:
      - env:
        - name: nofile
          value: "262144"
        - name: privileged
          value: "true"
        - name: ulimit
          value: "262144"
        image: clickhouse/clickhouse-server:22.1.4.30
        imagePullPolicy: Always
        name: clickhouse
        ports:
        - containerPort: 8123
          name: clickhouse8123
          protocol: TCP
        - containerPort: 9000
          name: clickhouse9000
          protocol: TCP
        - containerPort: 9009
          name: clickhouse9009
          protocol: TCP
        resources: {}
        securityContext:
          allowPrivilegeEscalation: false
          capabilities: {}
          privileged: false
          readOnlyRootFilesystem: false
          runAsNonRoot: false
        stdin: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        tty: true
        volumeMounts:
        - mountPath: /var/log/clickhouse-server
          name: clickhouse-log
        - mountPath: /var/lib/clickhouse
          name: clickhouse-data
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - hostPath:
          path: /mydata/docker/clickhouse/log
          type: DirectoryOrCreate
        name: clickhouse-log
      - hostPath:
          path: /mydata/docker/clickhouse/data
          type: DirectoryOrCreate
        name: clickhouse-data
status: {}
