apiVersion: apps/v1
kind: Deployment
metadata:
  name: flink-taskmanager
  namespace: flink
  labels:
    app: flink
    component: taskmanager
spec:
  replicas: 2
  selector:
    matchLabels:
      app: flink
  template:
    metadata:
      labels:
        app: flink
        component: taskmanager
    spec:
      containers:
      - name: taskmanager
        image: flink:1.13-scala_2.11-java11
        args:
        - taskmanager
        - "-Dtaskmanager.host=$(K8S_POD_IP)"
        - "-Dtaskmanager.numberOfTaskSlots=6"
        ports:
        - containerPort: 6121
          name: data
        - containerPort: 6122
          name: rpc
        - containerPort: 6125
          name: query
        env:
        - name: JOB_MANAGER_RPC_ADDRESS
          value: flink-jobmanager
        - name: K8S_POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP

